//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDR_MAIN                        7
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_DEMO                        157
#define IDB_DEMO2                       158
#define IDB_CHARACTER                   159
#define IDB_BLUE                        162
#define IDB_BITMAP4                     163
#define IDB_GREEN                       163
#define BACKGROUND                      164
#define IDB_BITMAP5                     166
#define IDB_START                       166
#define IDB_GameMAP                     167
#define GAMEMAP                         167
#define ANTHONY1                        168
#define IDB_BITMAP3                     169
#define IDB_BITMAP6                     170
#define ANTHONY2                        171
#define ANTHONY3                        172
#define IDB_BITMAP7                     173
#define IDB_BITMAP8                     174
#define ANTHONY4                        174
#define IDB_BITMAP9                     175
#define SELECT                          175
#define E_Bat1_1                        176
#define IDB_BITMAP11                    177
#define E_Bat1_2                        177
#define IDB_BITMAP13                    180
#define BLOOD                           180
#define IDB_BITMAP10                    182
#define WHIP_1_2                        182
#define IDB_BITMAP12                    183
#define WHIP_1_B                        183
#define skill_WHIP_B                    183
#define IDB_BITMAP14                    184
#define IDB_BITMAP15                    189
#define GRAY_BLOOD                      189
#define skill_Rwhip_1_1                 190
#define skill_Lwhip_2_1                 191
#define skill_Lwhip_2_2                 192
#define skill_Rwhip_2_1                 193
#define skill_Rwhip_2_                  194
#define skill_Rwhip_2_2                 194
#define skill_Lwhip_3_1                 196
#define skill_Lwhip_3_2                 197
#define skill_Lwhip_3_3                 198
#define skill_Rwhip_3_1                 199
#define skill_Rwhip_3_2                 200
#define skill_Rwhip_3_3                 201
#define skill_Lwhip_4_1                 202
#define skill_Lwhip_4_2                 203
#define skill_Lwhip_4_3                 204
#define skill_Lwhip_4_4                 205
#define skill_Rwhip_4_1                 206
#define skill_Rwhip_4_2                 207
#define skill_Rwhip_4_3                 208
#define skill_Rwhip_4_4                 209
#define skill_Lwhip_5_5                 210
#define IDB_BITMAP17                    211
#define skill_Rwhip_5_5                 211
#define timer_0                         212
#define timer_1                         213
#define timer_2                         214
#define timer_3                         215
#define timer_4                         216
#define timer_5                         217
#define timer_6                         218
#define timer_7                         219
#define timer_8                         220
#define timer_9                         221
#define IDB_BITMAP27                    222
#define timer_dot                       222
#define IDB_BITMAP16                    223
#define IDB_BITMAP18                    224
#define IDB_BITMAP19                    225
#define EXP                             225
#define expBar_bg                       226
#define IDB_BITMAP21                    227
#define expBar_exp                      227
#define IDI_ICON1                       228
#define btn_abotUs                      229
#define btn_howToPlay                   230
#define IDB_BITMAP23                    231
#define btn_start                       231
#define AboutView                       232
#define IDB_BITMAP22                    233
#define HowView                         233
#define OVER                            234
#define OVERBACKGROUND                  234
#define overBG                          234
#define btn_done                        235
#define IDB_BITMAP24                    236
#define img_result                      236
#define death_R_1                       237
#define death_R_2                       238
#define death_R_3                       239
#define death_R_4                       240
#define death_L_1                       241
#define death_L_2                       242
#define death_L_3                       243
#define IDB_BITMAP32                    244
#define death_L_4                       244
#define deathBackGroung                 245
#define gameoverTitle                   246
#define stageclaerTitle                 247
#define IDB_BITMAP20                    248
#define endBtn                          248
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775
#define WHIP_1_1                        58112
#define skill_Lwhip_1_1                 58112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        249
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
